machine:
  services:
    - docker

dependencies:
  cache_directories:
    - ~/docker

deployment:
  staging:
    branch: master
    commands:
      - docker login --email=$HEROKU_USERNAME --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
      - docker build --rm=false -t registry.heroku.com/APP_NAME/web .
      - docker push registry.heroku.com/APP_NAME/web:latest